global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alertas'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: 'OnlyWave Alertas'
        actions:
          - type: button
            text: 'Ver no Grafana'
            url: '{{ template "slack.default.grafana" . }}'

  - name: 'slack-critical'
    slack_configs:
      - channel: '#alertas-criticos'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: 'OnlyWave Alertas Críticos'
        actions:
          - type: button
            text: 'Ver no Grafana'
            url: '{{ template "slack.default.grafana" . }}'

templates:
  - '/etc/alertmanager/template/*.tmpl'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']

  - name: 'slack-critical'
    slack_configs:
      - channel: '#alertas-criticos'
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        footer: 'OnlyWave Payment Service - CRÍTICO'
        actions:
          - type: button
            text: 'Ver Dashboard'
            url: 'http://grafana:3000/d/payment/payment-service' 