groups:
  - name: auth_service
    rules:
      # Tentativas de login suspeitas
      - alert: SuspiciousLoginAttempts
        expr: rate(auth_login_attempts_total{status="failed"}[5m]) > 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Tentativas de login suspeitas"
          description: "Mais de 10 tentativas de login falhas por minuto"
          value: "{{ $value }} tentativas/min"

      # Tokens expirados
      - alert: HighTokenExpirationRate
        expr: rate(auth_token_expirations_total[5m]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alta taxa de expiração de tokens"
          description: "Mais de 5 tokens expiram por minuto"
          value: "{{ $value }} tokens/min"

      # Latência de autenticação
      - alert: HighAuthLatency
        expr: histogram_quantile(0.95, rate(auth_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Latência alta na autenticação"
          description: "O serviço de autenticação está com latência acima de 500ms no percentil 95"
          value: "{{ $value }}s"

      # Erros de validação
      - alert: HighValidationErrors
        expr: rate(auth_validation_errors_total[5m]) > 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Muitos erros de validação"
          description: "Mais de 20 erros de validação por minuto"
          value: "{{ $value }} erros/min" 