groups:
  - name: payment_alerts
    rules:
      - alert: HighPaymentFailureRate
        expr: rate(payment_total{status="failed"}[5m]) / rate(payment_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Taxa de falha em pagamentos acima de 10% nos últimos 5 minutos"
          value: "{{ $value }}%"

      - alert: HighProcessingTime
        expr: histogram_quantile(0.95, rate(payment_processing_duration_seconds_bucket[5m])) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "Tempo de processamento de pagamentos (P95) acima de 5 segundos"
          value: "{{ $value }}s"

      - alert: WebhookQueueSize
        expr: webhook_queue_size > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "Fila de webhooks com mais de 1000 mensagens pendentes"
          value: "{{ $value }} mensagens"

      - alert: HighCacheErrorRate
        expr: rate(cache_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Taxa de erros de cache acima de 10% nos últimos 5 minutos"
          value: "{{ $value }}%"

      - alert: EventPublishFailures
        expr: rate(event_publish_failures_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Falhas na publicação de eventos"
          description: "Taxa de falhas na publicação de eventos está acima de 5% nos últimos 5 minutos"
          value: "{{ $value }}%"

      - alert: PaymentServiceDown
        expr: up{job="payment-service"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Serviço de pagamentos indisponível"
          description: "O serviço de pagamentos está fora do ar há mais de 1 minuto"

  - name: payment_service
    rules:
      # Latência alta
      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Latência alta detectada"
          description: "O serviço está com latência acima de 1 segundo no percentil 95"
          value: "{{ $value }}s"

      # Taxa de erro alta
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Taxa de erro alta"
          description: "Mais de 5% das requisições estão resultando em erro 5xx"
          value: "{{ $value | humanizePercentage }}"

      # Memória alta
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 > 1024
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Uso de memória alto"
          description: "O processo está usando mais de 1GB de memória"
          value: "{{ $value | humanize }}MB"

      # CPU alta
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Uso de CPU alto"
          description: "O processo está usando mais de 80% de CPU"
          value: "{{ $value | humanizePercentage }}"

      # Conexões de banco de dados
      - alert: HighDatabaseConnections
        expr: pg_stat_activity_count > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Muitas conexões de banco"
          description: "Mais de 100 conexões ativas no banco de dados"
          value: "{{ $value }} conexões" 