groups:
  - name: user_service
    rules:
      # Alta taxa de criação de usuários
      - alert: HighUserCreationRate
        expr: rate(user_creation_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alta taxa de criação de usuários"
          description: "Mais de 10 usuários sendo criados por minuto"
          value: "{{ $value }} usuários/min"

      # Erros de validação de usuário
      - alert: HighUserValidationErrors
        expr: rate(user_validation_errors_total[5m]) > 15
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Muitos erros de validação de usuário"
          description: "Mais de 15 erros de validação por minuto"
          value: "{{ $value }} erros/min"

      # Latência de operações de usuário
      - alert: HighUserOperationLatency
        expr: histogram_quantile(0.95, rate(user_operation_duration_seconds_bucket[5m])) > 0.3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Latência alta em operações de usuário"
          description: "Operações de usuário com latência acima de 300ms no percentil 95"
          value: "{{ $value }}s"

      # Falhas de atualização de usuário
      - alert: HighUserUpdateFailures
        expr: rate(user_update_failures_total[5m]) > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Muitas falhas na atualização de usuários"
          description: "Mais de 5 falhas na atualização de usuários por minuto"
          value: "{{ $value }} falhas/min"
          
      # Pico de falhas de autenticação
      - alert: AuthenticationSpike
        expr: rate(user_auth_failures_total[1m]) > 20
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Pico de falhas de autenticação detectado"
          description: "Possível tentativa de força bruta detectada - mais de 20 falhas de autenticação por minuto"
          value: "{{ $value }} falhas/min"
          
      # Erros na geração de tokens
      - alert: TokenGenerationErrors
        expr: rate(user_token_generation_failures_total[1m]) > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Erros na geração de tokens"
          description: "Mais de 5 falhas na geração de tokens por minuto"
          value: "{{ $value }} falhas/min"
          
      # Latência alta no login
      - alert: HighLoginLatency
        expr: histogram_quantile(0.95, rate(user_login_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Latência alta no processo de login"
          description: "Login com latência acima de 500ms no percentil 95"
          value: "{{ $value }}s"
          
      # Queda brusca de sessões ativas
      - alert: SuddenDropInUserSessions
        expr: delta(user_active_sessions[5m]) < -50
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Queda brusca no número de sessões ativas"
          description: "Mais de 50 sessões de usuário foram encerradas em 5 minutos"
          value: "{{ $value }} sessões" 